2022-06-13 11:39:55,369 - middleware.py[line:51] - INFO: Enabled downloader middlewares:
['Qinghai.middlewares.RandomIPMiddleware',
 'Qinghai.middlewares.RandomUserAgentMiddleware',
 'scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2022-06-13 11:39:55,372 - middleware.py[line:51] - INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2022-06-13 11:39:55,374 - middleware.py[line:51] - INFO: Enabled item pipelines:
['Qinghai.pipelines.QinghaiPipeline']
2022-06-13 11:39:55,375 - engine.py[line:313] - INFO: Spider opened
2022-06-13 11:39:55,602 - logstats.py[line:48] - INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2022-06-13 11:39:55,603 - telnet.py[line:67] - INFO: Telnet console listening on 127.0.0.1:6023
2022-06-13 11:39:55,605 - middlewares.py[line:184] - INFO: 使用代理[123.144.151.87:4246]访问[http://www.59med.com/news/list.php?catid=26&page=1]
2022-06-13 11:39:55,607 - middlewares.py[line:184] - INFO: 使用代理[123.158.99.245:4224]访问[http://www.59med.com/news/list.php?catid=26&page=2]
2022-06-13 11:39:55,607 - middlewares.py[line:184] - INFO: 使用代理[221.201.197.219:4231]访问[http://www.59med.com/news/list.php?catid=26&page=3]
2022-06-13 11:39:55,609 - middlewares.py[line:184] - INFO: 使用代理[123.155.203.93:4237]访问[http://www.59med.com/news/list.php?catid=26&page=4]
2022-06-13 11:39:55,609 - middlewares.py[line:184] - INFO: 使用代理[121.29.81.63:4231]访问[http://www.59med.com/news/list.php?catid=26&page=5]
2022-06-13 11:39:55,609 - middlewares.py[line:184] - INFO: 使用代理[119.112.89.37:4253]访问[http://www.59med.com/news/list.php?catid=26&page=6]
2022-06-13 11:39:55,609 - middlewares.py[line:184] - INFO: 使用代理[175.146.102.173:4231]访问[http://www.59med.com/news/list.php?catid=26&page=7]
2022-06-13 11:39:55,768 - middlewares.py[line:184] - INFO: 使用代理[116.115.209.177:4231]访问[http://www.59med.com/news/list.php?catid=26&page=1]
2022-06-13 11:40:00,028 - retry.py[line:96] - DEBUG: Retrying <GET http://www.59med.com/news/list.php?catid=26&page=1> (failed 1 times): Connection was refused by other side: 10061: 由于目标计算机积极拒绝，无法连接。.
2022-06-13 11:40:00,028 - middlewares.py[line:184] - INFO: 使用代理[123.144.146.184:4235]访问[http://www.59med.com/news/list.php?catid=26&page=1]
2022-06-13 11:40:00,184 - middlewares.py[line:184] - INFO: 使用代理[116.115.210.179:4231]访问[http://www.59med.com/news/list.php?catid=26&page=1]
2022-06-13 11:40:04,859 - retry.py[line:96] - DEBUG: Retrying <GET http://www.59med.com/news/list.php?catid=26&page=7> (failed 1 times): Connection was refused by other side: 10061: 由于目标计算机积极拒绝，无法连接。.
2022-06-13 11:40:04,859 - middlewares.py[line:184] - INFO: 使用代理[121.29.81.63:4231]访问[http://www.59med.com/news/list.php?catid=26&page=7]
2022-06-13 11:40:17,102 - retry.py[line:96] - DEBUG: Retrying <GET http://www.59med.com/news/list.php?catid=26&page=2> (failed 1 times): TCP connection timed out: 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2022-06-13 11:40:17,104 - middlewares.py[line:184] - INFO: 使用代理[42.56.237.193:4216]访问[http://www.59med.com/news/list.php?catid=26&page=2]
2022-06-13 11:40:17,339 - retry.py[line:96] - DEBUG: Retrying <GET http://www.59med.com/news/list.php?catid=26&page=3> (failed 1 times): TCP connection timed out: 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2022-06-13 11:40:17,340 - middlewares.py[line:184] - INFO: 使用代理[120.2.1.2:4231]访问[http://www.59med.com/news/list.php?catid=26&page=3]
2022-06-13 11:40:17,700 - retry.py[line:96] - DEBUG: Retrying <GET http://www.59med.com/news/list.php?catid=26&page=4> (failed 1 times): TCP connection timed out: 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2022-06-13 11:40:17,701 - middlewares.py[line:184] - INFO: 使用代理[175.146.215.46:4256]访问[http://www.59med.com/news/list.php?catid=26&page=4]
2022-06-13 11:40:17,998 - retry.py[line:96] - DEBUG: Retrying <GET http://www.59med.com/news/list.php?catid=26&page=5> (failed 1 times): TCP connection timed out: 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2022-06-13 11:40:17,999 - middlewares.py[line:184] - INFO: 使用代理[175.147.119.82:4232]访问[http://www.59med.com/news/list.php?catid=26&page=5]
2022-06-13 11:40:18,249 - retry.py[line:96] - DEBUG: Retrying <GET http://www.59med.com/news/list.php?catid=26&page=6> (failed 1 times): TCP connection timed out: 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2022-06-13 11:40:18,250 - middlewares.py[line:184] - INFO: 使用代理[101.27.197.197:4231]访问[http://www.59med.com/news/list.php?catid=26&page=6]
2022-06-13 11:40:19,267 - retry.py[line:96] - DEBUG: Retrying <GET http://www.59med.com/news/list.php?catid=26&page=2> (failed 2 times): Connection was refused by other side: 10061: 由于目标计算机积极拒绝，无法连接。.
2022-06-13 11:40:19,268 - middlewares.py[line:184] - INFO: 使用代理[119.5.37.119:4231]访问[http://www.59med.com/news/list.php?catid=26&page=2]
2022-06-13 11:40:19,494 - middlewares.py[line:184] - INFO: 使用代理[113.229.173.6:4231]访问[http://www.59med.com/news/list.php?catid=26&page=2]
2022-06-13 11:40:19,992 - retry.py[line:96] - DEBUG: Retrying <GET http://www.59med.com/news/list.php?catid=26&page=4> (failed 2 times): Connection was refused by other side: 10061: 由于目标计算机积极拒绝，无法连接。.
2022-06-13 11:40:19,992 - middlewares.py[line:184] - INFO: 使用代理[123.144.146.184:4235]访问[http://www.59med.com/news/list.php?catid=26&page=4]
2022-06-13 11:40:20,144 - middlewares.py[line:184] - INFO: 使用代理[110.18.2.133:4234]访问[http://www.59med.com/news/list.php?catid=26&page=4]
2022-06-13 11:40:21,387 - retry.py[line:96] - DEBUG: Retrying <GET http://www.59med.com/news/list.php?catid=26&page=1> (failed 2 times): TCP connection timed out: 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2022-06-13 11:40:21,388 - middlewares.py[line:184] - INFO: 使用代理[58.243.28.23:4231]访问[http://www.59med.com/news/list.php?catid=26&page=1]
2022-06-13 11:40:21,467 - middlewares.py[line:184] - INFO: 使用代理[116.115.210.179:4231]访问[http://www.59med.com/news/list.php?catid=26&page=1]
2022-06-13 11:40:21,846 - retry.py[line:118] - ERROR: Gave up retrying <GET http://www.59med.com/news/list.php?catid=26&page=2> (failed 3 times): Connection was refused by other side: 10061: 由于目标计算机积极拒绝，无法连接。.
2022-06-13 11:40:21,846 - middlewares.py[line:184] - INFO: 使用代理[42.59.160.3:4278]访问[http://www.59med.com/news/list.php?catid=26&page=2]
2022-06-13 11:40:24,615 - engine.py[line:291] - DEBUG: Crawled (200) <GET http://www.59med.com/news/list.php?catid=26&page=5> (referer: None)
2022-06-13 11:40:25,894 - retry.py[line:96] - DEBUG: Retrying <GET http://www.59med.com/news/list.php?catid=26&page=7> (failed 2 times): TCP connection timed out: 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2022-06-13 11:40:25,895 - middlewares.py[line:184] - INFO: 使用代理[113.237.240.24:4261]访问[http://www.59med.com/news/list.php?catid=26&page=7]
2022-06-13 11:40:26,382 - engine.py[line:291] - DEBUG: Crawled (200) <GET http://www.59med.com/news/list.php?catid=26&page=7> (referer: None)
2022-06-13 11:40:29,811 - retry.py[line:118] - ERROR: Gave up retrying <GET http://www.59med.com/news/list.php?catid=26&page=2> (failed 3 times): Connection was refused by other side: 10061: 由于目标计算机积极拒绝，无法连接。.
2022-06-13 11:40:29,811 - middlewares.py[line:184] - INFO: 使用代理[175.173.223.183:4213]访问[http://www.59med.com/news/list.php?catid=26&page=2]
2022-06-13 11:40:32,013 - retry.py[line:118] - ERROR: Gave up retrying <GET http://www.59med.com/news/list.php?catid=26&page=2> (failed 3 times): Connection was refused by other side: 10061: 由于目标计算机积极拒绝，无法连接。.
2022-06-13 11:40:32,013 - middlewares.py[line:184] - INFO: 使用代理[113.228.107.76:4231]访问[http://www.59med.com/news/list.php?catid=26&page=2]
2022-06-13 11:40:38,556 - retry.py[line:96] - DEBUG: Retrying <GET http://www.59med.com/news/list.php?catid=26&page=3> (failed 2 times): TCP connection timed out: 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2022-06-13 11:40:38,558 - middlewares.py[line:184] - INFO: 使用代理[110.18.2.133:4234]访问[http://www.59med.com/news/list.php?catid=26&page=3]
2022-06-13 11:40:39,599 - retry.py[line:96] - DEBUG: Retrying <GET http://www.59med.com/news/list.php?catid=26&page=6> (failed 2 times): TCP connection timed out: 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2022-06-13 11:40:39,599 - middlewares.py[line:184] - INFO: 使用代理[175.146.215.46:4256]访问[http://www.59med.com/news/list.php?catid=26&page=6]
2022-06-13 11:40:41,525 - retry.py[line:118] - ERROR: Gave up retrying <GET http://www.59med.com/news/list.php?catid=26&page=4> (failed 3 times): TCP connection timed out: 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2022-06-13 11:40:41,526 - middlewares.py[line:184] - INFO: 使用代理[42.59.160.3:4278]访问[http://www.59med.com/news/list.php?catid=26&page=4]
2022-06-13 11:40:41,767 - retry.py[line:118] - ERROR: Gave up retrying <GET http://www.59med.com/news/list.php?catid=26&page=6> (failed 3 times): Connection was refused by other side: 10061: 由于目标计算机积极拒绝，无法连接。.
2022-06-13 11:40:41,768 - middlewares.py[line:184] - INFO: 使用代理[42.57.148.87:4267]访问[http://www.59med.com/news/list.php?catid=26&page=6]
2022-06-13 11:40:42,758 - retry.py[line:118] - ERROR: Gave up retrying <GET http://www.59med.com/news/list.php?catid=26&page=1> (failed 3 times): TCP connection timed out: 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2022-06-13 11:40:42,759 - middlewares.py[line:184] - INFO: 使用代理[175.146.102.173:4231]访问[http://www.59med.com/news/list.php?catid=26&page=1]
2022-06-13 11:40:42,955 - engine.py[line:291] - DEBUG: Crawled (200) <GET http://www.59med.com/news/list.php?catid=26&page=6> (referer: None)
2022-06-13 11:40:44,235 - retry.py[line:118] - ERROR: Gave up retrying <GET http://www.59med.com/news/list.php?catid=26&page=4> (failed 3 times): Connection was refused by other side: 10061: 由于目标计算机积极拒绝，无法连接。.
2022-06-13 11:40:44,235 - middlewares.py[line:184] - INFO: 使用代理[116.115.210.179:4231]访问[http://www.59med.com/news/list.php?catid=26&page=4]
2022-06-13 11:40:45,082 - retry.py[line:118] - ERROR: Gave up retrying <GET http://www.59med.com/news/list.php?catid=26&page=1> (failed 3 times): Connection was refused by other side: 10061: 由于目标计算机积极拒绝，无法连接。.
2022-06-13 11:40:45,082 - middlewares.py[line:184] - INFO: 使用代理[42.85.235.163:4256]访问[http://www.59med.com/news/list.php?catid=26&page=1]
2022-06-13 11:40:53,054 - retry.py[line:118] - ERROR: Gave up retrying <GET http://www.59med.com/news/list.php?catid=26&page=2> (failed 3 times): TCP connection timed out: 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2022-06-13 11:40:53,055 - middlewares.py[line:184] - INFO: 使用代理[113.229.173.6:4231]访问[http://www.59med.com/news/list.php?catid=26&page=2]
2022-06-13 11:40:55,235 - retry.py[line:118] - ERROR: Gave up retrying <GET http://www.59med.com/news/list.php?catid=26&page=2> (failed 3 times): Connection was refused by other side: 10061: 由于目标计算机积极拒绝，无法连接。.
2022-06-13 11:40:55,236 - middlewares.py[line:184] - INFO: 使用代理[42.59.160.3:4278]访问[http://www.59med.com/news/list.php?catid=26&page=2]
2022-06-13 11:40:55,610 - logstats.py[line:48] - INFO: Crawled 3 pages (at 3 pages/min), scraped 0 items (at 0 items/min)
2022-06-13 11:40:57,779 - retry.py[line:118] - ERROR: Gave up retrying <GET http://www.59med.com/news/list.php?catid=26&page=2> (failed 3 times): Connection was refused by other side: 10061: 由于目标计算机积极拒绝，无法连接。.
2022-06-13 11:40:57,780 - middlewares.py[line:184] - INFO: 使用代理[119.249.41.226:4223]访问[http://www.59med.com/news/list.php?catid=26&page=2]
2022-06-13 11:40:59,591 - retry.py[line:118] - ERROR: Gave up retrying <GET http://www.59med.com/news/list.php?catid=26&page=3> (failed 3 times): TCP connection timed out: 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2022-06-13 11:40:59,592 - middlewares.py[line:184] - INFO: 使用代理[113.237.185.131:4261]访问[http://www.59med.com/news/list.php?catid=26&page=3]
2022-06-13 11:41:01,752 - retry.py[line:118] - ERROR: Gave up retrying <GET http://www.59med.com/news/list.php?catid=26&page=3> (failed 3 times): Connection was refused by other side: 10061: 由于目标计算机积极拒绝，无法连接。.
2022-06-13 11:41:01,752 - middlewares.py[line:184] - INFO: 使用代理[175.149.61.52:4243]访问[http://www.59med.com/news/list.php?catid=26&page=3]
2022-06-13 11:41:03,903 - retry.py[line:118] - ERROR: Gave up retrying <GET http://www.59med.com/news/list.php?catid=26&page=3> (failed 3 times): Connection was refused by other side: 10061: 由于目标计算机积极拒绝，无法连接。.
2022-06-13 11:41:03,903 - middlewares.py[line:184] - INFO: 使用代理[42.55.180.247:4231]访问[http://www.59med.com/news/list.php?catid=26&page=3]
2022-06-13 11:41:05,267 - retry.py[line:118] - ERROR: Gave up retrying <GET http://www.59med.com/news/list.php?catid=26&page=4> (failed 3 times): TCP connection timed out: 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2022-06-13 11:41:05,268 - middlewares.py[line:184] - INFO: 使用代理[101.70.255.26:4237]访问[http://www.59med.com/news/list.php?catid=26&page=4]
2022-06-13 11:41:06,078 - retry.py[line:118] - ERROR: Gave up retrying <GET http://www.59med.com/news/list.php?catid=26&page=3> (failed 3 times): Connection was refused by other side: 10061: 由于目标计算机积极拒绝，无法连接。.
2022-06-13 11:41:06,079 - middlewares.py[line:184] - INFO: 使用代理[42.59.101.204:4213]访问[http://www.59med.com/news/list.php?catid=26&page=3]
2022-06-13 11:41:06,113 - retry.py[line:118] - ERROR: Gave up retrying <GET http://www.59med.com/news/list.php?catid=26&page=1> (failed 3 times): TCP connection timed out: 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2022-06-13 11:41:06,114 - middlewares.py[line:184] - INFO: 使用代理[101.27.197.197:4231]访问[http://www.59med.com/news/list.php?catid=26&page=1]
2022-06-13 11:41:10,168 - retry.py[line:118] - ERROR: Gave up retrying <GET http://www.59med.com/news/list.php?catid=26&page=1> (failed 3 times): Connection was refused by other side: 10061: 由于目标计算机积极拒绝，无法连接。.
2022-06-13 11:41:10,169 - middlewares.py[line:184] - INFO: 使用代理[42.59.101.204:4213]访问[http://www.59med.com/news/list.php?catid=26&page=1]
2022-06-13 11:41:18,804 - retry.py[line:118] - ERROR: Gave up retrying <GET http://www.59med.com/news/list.php?catid=26&page=2> (failed 3 times): TCP connection timed out: 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2022-06-13 11:41:18,805 - middlewares.py[line:184] - INFO: 使用代理[42.56.237.193:4216]访问[http://www.59med.com/news/list.php?catid=26&page=2]
2022-06-13 11:41:21,508 - retry.py[line:118] - ERROR: Gave up retrying <GET http://www.59med.com/news/list.php?catid=26&page=2> (failed 3 times): Connection was refused by other side: 10061: 由于目标计算机积极拒绝，无法连接。.
2022-06-13 11:41:21,509 - middlewares.py[line:184] - INFO: 使用代理[42.63.132.45:4215]访问[http://www.59med.com/news/list.php?catid=26&page=2]
2022-06-13 11:41:26,303 - retry.py[line:118] - ERROR: Gave up retrying <GET http://www.59med.com/news/list.php?catid=26&page=4> (failed 3 times): TCP connection timed out: 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2022-06-13 11:41:26,304 - middlewares.py[line:184] - INFO: 使用代理[42.85.235.163:4256]访问[http://www.59med.com/news/list.php?catid=26&page=4]
2022-06-13 11:41:27,113 - retry.py[line:118] - ERROR: Gave up retrying <GET http://www.59med.com/news/list.php?catid=26&page=3> (failed 3 times): TCP connection timed out: 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2022-06-13 11:41:27,114 - middlewares.py[line:184] - INFO: 使用代理[60.20.206.120:4213]访问[http://www.59med.com/news/list.php?catid=26&page=3]
2022-06-13 11:41:29,363 - retry.py[line:118] - ERROR: Gave up retrying <GET http://www.59med.com/news/list.php?catid=26&page=3> (failed 3 times): Connection was refused by other side: 10061: 由于目标计算机积极拒绝，无法连接。.
2022-06-13 11:41:29,363 - middlewares.py[line:184] - INFO: 使用代理[175.149.61.52:4243]访问[http://www.59med.com/news/list.php?catid=26&page=3]
2022-06-13 11:41:31,196 - retry.py[line:118] - ERROR: Gave up retrying <GET http://www.59med.com/news/list.php?catid=26&page=1> (failed 3 times): TCP connection timed out: 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2022-06-13 11:41:31,197 - middlewares.py[line:184] - INFO: 使用代理[101.70.255.26:4237]访问[http://www.59med.com/news/list.php?catid=26&page=1]
2022-06-13 11:41:31,542 - retry.py[line:118] - ERROR: Gave up retrying <GET http://www.59med.com/news/list.php?catid=26&page=3> (failed 3 times): Connection was refused by other side: 10061: 由于目标计算机积极拒绝，无法连接。.
2022-06-13 11:41:31,543 - middlewares.py[line:184] - INFO: 使用代理[101.27.197.197:4231]访问[http://www.59med.com/news/list.php?catid=26&page=3]
2022-06-13 11:41:41,295 - retry.py[line:118] - ERROR: Gave up retrying <GET http://www.59med.com/news/list.php?catid=26&page=3> (failed 3 times): Connection was refused by other side: 10061: 由于目标计算机积极拒绝，无法连接。.
2022-06-13 11:41:41,296 - middlewares.py[line:184] - INFO: 使用代理[120.2.1.2:4231]访问[http://www.59med.com/news/list.php?catid=26&page=3]
2022-06-13 11:41:42,560 - retry.py[line:118] - ERROR: Gave up retrying <GET http://www.59med.com/news/list.php?catid=26&page=2> (failed 3 times): TCP connection timed out: 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2022-06-13 11:41:42,560 - middlewares.py[line:184] - INFO: 使用代理[42.55.180.247:4231]访问[http://www.59med.com/news/list.php?catid=26&page=2]
2022-06-13 11:41:44,782 - retry.py[line:118] - ERROR: Gave up retrying <GET http://www.59med.com/news/list.php?catid=26&page=2> (failed 3 times): Connection was refused by other side: 10061: 由于目标计算机积极拒绝，无法连接。.
2022-06-13 11:41:44,782 - middlewares.py[line:184] - INFO: 使用代理[42.59.100.153:4231]访问[http://www.59med.com/news/list.php?catid=26&page=2]
2022-06-13 11:41:47,343 - retry.py[line:118] - ERROR: Gave up retrying <GET http://www.59med.com/news/list.php?catid=26&page=4> (failed 3 times): TCP connection timed out: 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2022-06-13 11:41:47,344 - middlewares.py[line:184] - INFO: 使用代理[113.228.107.76:4231]访问[http://www.59med.com/news/list.php?catid=26&page=4]
2022-06-13 11:41:52,220 - retry.py[line:118] - ERROR: Gave up retrying <GET http://www.59med.com/news/list.php?catid=26&page=1> (failed 3 times): TCP connection timed out: 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2022-06-13 11:41:52,221 - middlewares.py[line:184] - INFO: 使用代理[123.144.61.224:4235]访问[http://www.59med.com/news/list.php?catid=26&page=1]
2022-06-13 11:41:52,385 - middlewares.py[line:184] - INFO: 使用代理[123.144.61.224:4235]访问[http://www.59med.com/news/list.php?catid=26&page=1]
2022-06-13 11:41:52,710 - middlewares.py[line:184] - INFO: 使用代理[110.18.2.133:4234]访问[http://www.59med.com/news/list.php?catid=26&page=1]
2022-06-13 11:41:55,614 - logstats.py[line:48] - INFO: Crawled 3 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2022-06-13 11:42:02,336 - retry.py[line:118] - ERROR: Gave up retrying <GET http://www.59med.com/news/list.php?catid=26&page=3> (failed 3 times): TCP connection timed out: 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2022-06-13 11:42:02,337 - middlewares.py[line:184] - INFO: 使用代理[113.228.107.76:4231]访问[http://www.59med.com/news/list.php?catid=26&page=3]
2022-06-13 11:42:05,841 - retry.py[line:118] - ERROR: Gave up retrying <GET http://www.59med.com/news/list.php?catid=26&page=2> (failed 3 times): TCP connection timed out: 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2022-06-13 11:42:05,842 - middlewares.py[line:184] - INFO: 使用代理[123.155.203.93:4237]访问[http://www.59med.com/news/list.php?catid=26&page=2]
2022-06-13 11:42:08,375 - retry.py[line:118] - ERROR: Gave up retrying <GET http://www.59med.com/news/list.php?catid=26&page=4> (failed 3 times): TCP connection timed out: 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2022-06-13 11:42:08,376 - middlewares.py[line:184] - INFO: 使用代理[175.173.221.78:4220]访问[http://www.59med.com/news/list.php?catid=26&page=4]
2022-06-13 11:42:10,631 - retry.py[line:118] - ERROR: Gave up retrying <GET http://www.59med.com/news/list.php?catid=26&page=4> (failed 3 times): Connection was refused by other side: 10061: 由于目标计算机积极拒绝，无法连接。.
2022-06-13 11:42:10,631 - middlewares.py[line:184] - INFO: 使用代理[42.63.132.45:4215]访问[http://www.59med.com/news/list.php?catid=26&page=4]
2022-06-13 11:42:14,048 - retry.py[line:118] - ERROR: Gave up retrying <GET http://www.59med.com/news/list.php?catid=26&page=1> (failed 3 times): TCP connection timed out: 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2022-06-13 11:42:14,049 - middlewares.py[line:184] - INFO: 使用代理[175.147.119.82:4232]访问[http://www.59med.com/news/list.php?catid=26&page=1]
2022-06-13 11:42:14,323 - retry.py[line:118] - ERROR: Gave up retrying <GET http://www.59med.com/news/list.php?catid=26&page=1> (failed 3 times): [<twisted.python.failure.Failure twisted.internet.error.ConnectionDone: Connection was closed cleanly.>]
2022-06-13 11:42:14,323 - middlewares.py[line:184] - INFO: 使用代理[116.115.209.177:4231]访问[http://www.59med.com/news/list.php?catid=26&page=1]
2022-06-13 11:42:16,598 - retry.py[line:118] - ERROR: Gave up retrying <GET http://www.59med.com/news/list.php?catid=26&page=1> (failed 3 times): Connection was refused by other side: 10061: 由于目标计算机积极拒绝，无法连接。.
2022-06-13 11:42:16,598 - middlewares.py[line:184] - INFO: 使用代理[153.36.73.221:4278]访问[http://www.59med.com/news/list.php?catid=26&page=1]
2022-06-13 11:42:16,752 - middlewares.py[line:184] - INFO: 使用代理[121.29.83.20:4242]访问[http://www.59med.com/news/list.php?catid=26&page=1]
2022-06-13 11:42:18,973 - retry.py[line:118] - ERROR: Gave up retrying <GET http://www.59med.com/news/list.php?catid=26&page=1> (failed 3 times): Connection was refused by other side: 10061: 由于目标计算机积极拒绝，无法连接。.
2022-06-13 11:42:18,974 - middlewares.py[line:184] - INFO: 使用代理[113.237.240.24:4261]访问[http://www.59med.com/news/list.php?catid=26&page=1]
2022-06-13 11:42:19,759 - engine.py[line:291] - DEBUG: Crawled (200) <GET http://www.59med.com/news/list.php?catid=26&page=1> (referer: None)
2022-06-13 11:42:19,873 - middlewares.py[line:184] - INFO: 使用代理[110.18.2.133:4234]访问[http://www.59med.com/news/show.php?itemid=133659]
2022-06-13 11:42:19,874 - middlewares.py[line:184] - INFO: 使用代理[123.144.151.87:4246]访问[http://www.59med.com/news/show.php?itemid=133660]
2022-06-13 11:42:19,874 - middlewares.py[line:184] - INFO: 使用代理[123.155.203.93:4237]访问[http://www.59med.com/news/show.php?itemid=133661]
2022-06-13 11:42:19,875 - middlewares.py[line:184] - INFO: 使用代理[113.237.240.24:4261]访问[http://www.59med.com/news/show.php?itemid=133662]
2022-06-13 11:42:19,875 - middlewares.py[line:184] - INFO: 使用代理[42.57.148.87:4267]访问[http://www.59med.com/news/show.php?itemid=133663]
2022-06-13 11:42:19,875 - middlewares.py[line:184] - INFO: 使用代理[42.84.165.227:4251]访问[http://www.59med.com/news/show.php?itemid=133664]
2022-06-13 11:42:19,875 - middlewares.py[line:184] - INFO: 使用代理[175.173.223.183:4213]访问[http://www.59med.com/news/show.php?itemid=133665]
2022-06-13 11:42:19,876 - middlewares.py[line:184] - INFO: 使用代理[121.29.82.46:4231]访问[http://www.59med.com/news/show.php?itemid=133666]
2022-06-13 11:42:19,876 - middlewares.py[line:184] - INFO: 使用代理[113.237.185.131:4261]访问[http://www.59med.com/news/show.php?itemid=133667]
2022-06-13 11:42:19,876 - middlewares.py[line:184] - INFO: 使用代理[175.146.102.173:4231]访问[http://www.59med.com/news/show.php?itemid=133674]
2022-06-13 11:42:19,876 - middlewares.py[line:184] - INFO: 使用代理[113.237.240.24:4261]访问[http://www.59med.com/news/show.php?itemid=133676]
2022-06-13 11:42:19,876 - middlewares.py[line:184] - INFO: 使用代理[113.228.107.76:4231]访问[http://www.59med.com/news/show.php?itemid=133677]
2022-06-13 11:42:19,877 - middlewares.py[line:184] - INFO: 使用代理[123.144.62.135:4246]访问[http://www.59med.com/news/show.php?itemid=133678]
2022-06-13 11:42:20,367 - middlewares.py[line:184] - INFO: 使用代理[121.29.83.20:4242]访问[http://www.59med.com/news/show.php?itemid=133660]
2022-06-13 11:42:22,214 - engine.py[line:291] - DEBUG: Crawled (200) <GET http://www.59med.com/news/show.php?itemid=133663> (referer: http://www.59med.com/news/list.php?catid=26&page=1)
2022-06-13 11:42:22,217 - middlewares.py[line:184] - INFO: 使用代理[116.115.209.177:4231]访问[http://www.59med.com/news/show.php?itemid=133679]
2022-06-13 11:42:22,231 - engine.py[line:291] - DEBUG: Crawled (200) <GET http://www.59med.com/news/show.php?itemid=133662> (referer: http://www.59med.com/news/list.php?catid=26&page=1)
2022-06-13 11:42:22,232 - middlewares.py[line:184] - INFO: 使用代理[123.144.151.87:4246]访问[http://www.59med.com/news/show.php?itemid=133680]
2022-06-13 11:42:22,322 - scraper.py[line:275] - DEBUG: Scraped from <200 http://www.59med.com/news/show.php?itemid=133663>
None
2022-06-13 11:42:22,337 - scraper.py[line:275] - DEBUG: Scraped from <200 http://www.59med.com/news/show.php?itemid=133662>
None
2022-06-13 11:42:23,399 - retry.py[line:118] - ERROR: Gave up retrying <GET http://www.59med.com/news/list.php?catid=26&page=3> (failed 3 times): TCP connection timed out: 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2022-06-13 11:42:23,400 - middlewares.py[line:184] - INFO: 使用代理[123.144.146.184:4235]访问[http://www.59med.com/news/show.php?itemid=133681]
2022-06-13 11:42:23,441 - engine.py[line:291] - DEBUG: Crawled (200) <GET http://www.59med.com/news/show.php?itemid=133666> (referer: http://www.59med.com/news/list.php?catid=26&page=1)
2022-06-13 11:42:23,443 - middlewares.py[line:184] - INFO: 使用代理[113.237.240.24:4261]访问[http://www.59med.com/news/show.php?itemid=133682]
2022-06-13 11:42:23,555 - scraper.py[line:275] - DEBUG: Scraped from <200 http://www.59med.com/news/show.php?itemid=133666>
None
2022-06-13 11:42:24,381 - retry.py[line:96] - DEBUG: Retrying <GET http://www.59med.com/news/show.php?itemid=133665> (failed 1 times): Connection was refused by other side: 10061: 由于目标计算机积极拒绝，无法连接。.
2022-06-13 11:42:24,382 - middlewares.py[line:184] - INFO: 使用代理[101.27.197.197:4231]访问[http://www.59med.com/news/show.php?itemid=133683]
2022-06-13 11:42:24,887 - engine.py[line:291] - DEBUG: Crawled (200) <GET http://www.59med.com/news/show.php?itemid=133676> (referer: http://www.59med.com/news/list.php?catid=26&page=1)
2022-06-13 11:42:24,889 - middlewares.py[line:184] - INFO: 使用代理[101.27.201.223:4231]访问[http://www.59med.com/news/show.php?itemid=133684]
2022-06-13 11:42:24,995 - scraper.py[line:275] - DEBUG: Scraped from <200 http://www.59med.com/news/show.php?itemid=133676>
None
2022-06-13 11:42:25,570 - retry.py[line:96] - DEBUG: Retrying <GET http://www.59med.com/news/show.php?itemid=133667> (failed 1 times): Connection was refused by other side: 10061: 由于目标计算机积极拒绝，无法连接。.
2022-06-13 11:42:25,571 - middlewares.py[line:184] - INFO: 使用代理[42.7.5.66:4231]访问[http://www.59med.com/news/show.php?itemid=133690]
2022-06-13 11:42:26,014 - retry.py[line:96] - DEBUG: Retrying <GET http://www.59med.com/news/show.php?itemid=133674> (failed 1 times): Connection was refused by other side: 10061: 由于目标计算机积极拒绝，无法连接。.
2022-06-13 11:42:26,015 - middlewares.py[line:184] - INFO: 使用代理[123.158.99.245:4224]访问[http://www.59med.com/news/show.php?itemid=133674]
2022-06-13 11:42:26,896 - retry.py[line:118] - ERROR: Gave up retrying <GET http://www.59med.com/news/list.php?catid=26&page=2> (failed 3 times): TCP connection timed out: 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2022-06-13 11:42:26,896 - middlewares.py[line:184] - INFO: 使用代理[42.7.5.66:4231]访问[http://www.59med.com/news/show.php?itemid=133667]
2022-06-13 11:42:27,146 - engine.py[line:291] - DEBUG: Crawled (200) <GET http://www.59med.com/news/show.php?itemid=133678> (referer: http://www.59med.com/news/list.php?catid=26&page=1)
2022-06-13 11:42:27,149 - middlewares.py[line:184] - INFO: 使用代理[123.158.99.245:4224]访问[http://www.59med.com/news/show.php?itemid=133665]
2022-06-13 11:42:27,249 - scraper.py[line:275] - DEBUG: Scraped from <200 http://www.59med.com/news/show.php?itemid=133678>
None
2022-06-13 11:42:27,340 - middlewares.py[line:184] - INFO: 使用代理[101.27.201.223:4231]访问[http://www.59med.com/news/show.php?itemid=133680]
2022-06-13 11:42:27,807 - middlewares.py[line:184] - INFO: 使用代理[123.158.99.245:4224]访问[http://www.59med.com/news/show.php?itemid=133681]
2022-06-13 11:42:28,141 - retry.py[line:96] - DEBUG: Retrying <GET http://www.59med.com/news/show.php?itemid=133660> (failed 1 times): Connection was refused by other side: 10061: 由于目标计算机积极拒绝，无法连接。.
2022-06-13 11:42:28,141 - middlewares.py[line:184] - INFO: 使用代理[113.237.185.131:4261]访问[http://www.59med.com/news/show.php?itemid=133660]
2022-06-13 11:42:29,088 - retry.py[line:96] - DEBUG: Retrying <GET http://www.59med.com/news/show.php?itemid=133679> (failed 1 times): Connection was refused by other side: 10061: 由于目标计算机积极拒绝，无法连接。.
2022-06-13 11:42:29,089 - middlewares.py[line:184] - INFO: 使用代理[175.173.220.224:4210]访问[http://www.59med.com/news/show.php?itemid=133679]
2022-06-13 11:42:29,230 - engine.py[line:291] - DEBUG: Crawled (200) <GET http://www.59med.com/news/show.php?itemid=133682> (referer: http://www.59med.com/news/list.php?catid=26&page=1)
2022-06-13 11:42:29,233 - middlewares.py[line:184] - INFO: 使用代理[113.228.107.76:4231]访问[http://www.59med.com/news/list.php?catid=26&page=2]
2022-06-13 11:42:29,339 - scraper.py[line:275] - DEBUG: Scraped from <200 http://www.59med.com/news/show.php?itemid=133682>
None
2022-06-13 11:42:31,597 - retry.py[line:96] - DEBUG: Retrying <GET http://www.59med.com/news/show.php?itemid=133690> (failed 1 times): Connection was refused by other side: 10061: 由于目标计算机积极拒绝，无法连接。.
2022-06-13 11:42:31,598 - middlewares.py[line:184] - INFO: 使用代理[121.29.82.46:4231]访问[http://www.59med.com/news/show.php?itemid=133690]
2022-06-13 11:42:31,690 - retry.py[line:118] - ERROR: Gave up retrying <GET http://www.59med.com/news/list.php?catid=26&page=4> (failed 3 times): TCP connection timed out: 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2022-06-13 11:42:31,691 - middlewares.py[line:184] - INFO: 使用代理[121.29.83.20:4242]访问[http://www.59med.com/news/list.php?catid=26&page=4]
2022-06-13 11:42:34,145 - retry.py[line:96] - DEBUG: Retrying <GET http://www.59med.com/news/show.php?itemid=133667> (failed 2 times): Connection was refused by other side: 10061: 由于目标计算机积极拒绝，无法连接。.
2022-06-13 11:42:34,146 - middlewares.py[line:184] - INFO: 使用代理[123.144.146.184:4235]访问[http://www.59med.com/news/show.php?itemid=133667]
2022-06-13 11:42:36,655 - retry.py[line:96] - DEBUG: Retrying <GET http://www.59med.com/news/show.php?itemid=133683> (failed 1 times): TCP connection timed out: 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2022-06-13 11:42:36,655 - middlewares.py[line:184] - INFO: 使用代理[119.249.41.226:4223]访问[http://www.59med.com/news/show.php?itemid=133683]
2022-06-13 11:42:40,911 - retry.py[line:96] - DEBUG: Retrying <GET http://www.59med.com/news/show.php?itemid=133659> (failed 1 times): TCP connection timed out: 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2022-06-13 11:42:40,912 - middlewares.py[line:184] - INFO: 使用代理[119.249.41.226:4223]访问[http://www.59med.com/news/show.php?itemid=133659]
2022-06-13 11:42:41,743 - retry.py[line:96] - DEBUG: Retrying <GET http://www.59med.com/news/show.php?itemid=133661> (failed 1 times): TCP connection timed out: 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2022-06-13 11:42:41,744 - middlewares.py[line:184] - INFO: 使用代理[123.158.99.245:4224]访问[http://www.59med.com/news/show.php?itemid=133661]
2022-06-13 11:42:42,757 - retry.py[line:96] - DEBUG: Retrying <GET http://www.59med.com/news/show.php?itemid=133664> (failed 1 times): TCP connection timed out: 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2022-06-13 11:42:42,758 - middlewares.py[line:184] - INFO: 使用代理[42.84.165.227:4251]访问[http://www.59med.com/news/show.php?itemid=133664]
2022-06-13 11:42:43,102 - middlewares.py[line:184] - INFO: 使用代理[120.2.1.2:4231]访问[http://www.59med.com/news/show.php?itemid=133679]
2022-06-13 11:42:43,949 - retry.py[line:96] - DEBUG: Retrying <GET http://www.59med.com/news/show.php?itemid=133660> (failed 2 times): Connection was refused by other side: 10061: 由于目标计算机积极拒绝，无法连接。.
2022-06-13 11:42:43,950 - middlewares.py[line:184] - INFO: 使用代理[121.29.83.20:4242]访问[http://www.59med.com/news/show.php?itemid=133660]
2022-06-13 11:42:44,813 - engine.py[line:291] - DEBUG: Crawled (200) <GET http://www.59med.com/news/show.php?itemid=133690> (referer: http://www.59med.com/news/list.php?catid=26&page=1)
2022-06-13 11:42:44,815 - middlewares.py[line:184] - INFO: 使用代理[175.173.220.224:4210]访问[http://www.59med.com/news/list.php?catid=26&page=3]
2022-06-13 11:42:44,928 - scraper.py[line:275] - DEBUG: Scraped from <200 http://www.59med.com/news/show.php?itemid=133690>
None
2022-06-13 11:42:45,918 - retry.py[line:96] - DEBUG: Retrying <GET http://www.59med.com/news/show.php?itemid=133677> (failed 1 times): TCP connection timed out: 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2022-06-13 11:42:45,919 - middlewares.py[line:184] - INFO: 使用代理[175.173.220.224:4210]访问[http://www.59med.com/news/show.php?itemid=133677]
2022-06-13 11:42:46,001 - middlewares.py[line:184] - INFO: 使用代理[121.29.83.20:4242]访问[http://www.59med.com/news/show.php?itemid=133667]
2022-06-13 11:42:46,904 - retry.py[line:118] - ERROR: Gave up retrying <GET http://www.59med.com/news/list.php?catid=26&page=4> (failed 3 times): Connection was refused by other side: 10061: 由于目标计算机积极拒绝，无法连接。.
2022-06-13 11:42:46,905 - middlewares.py[line:184] - INFO: 使用代理[121.29.82.46:4231]访问[http://www.59med.com/news/list.php?catid=26&page=4]
2022-06-13 11:42:50,134 - retry.py[line:96] - DEBUG: Retrying <GET http://www.59med.com/news/show.php?itemid=133684> (failed 1 times): TCP connection timed out: 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2022-06-13 11:42:50,135 - middlewares.py[line:184] - INFO: 使用代理[113.228.107.76:4231]访问[http://www.59med.com/news/show.php?itemid=133684]
2022-06-13 11:42:52,638 - retry.py[line:96] - DEBUG: Retrying <GET http://www.59med.com/news/show.php?itemid=133674> (failed 2 times): TCP connection timed out: 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2022-06-13 11:42:52,639 - middlewares.py[line:184] - INFO: 使用代理[113.228.107.76:4231]访问[http://www.59med.com/news/show.php?itemid=133674]
2022-06-13 11:42:55,189 - retry.py[line:96] - DEBUG: Retrying <GET http://www.59med.com/news/show.php?itemid=133665> (failed 2 times): TCP connection timed out: 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2022-06-13 11:42:55,190 - middlewares.py[line:184] - INFO: 使用代理[113.228.107.76:4231]访问[http://www.59med.com/news/show.php?itemid=133665]
2022-06-13 11:42:55,607 - logstats.py[line:48] - INFO: Crawled 11 pages (at 8 pages/min), scraped 7 items (at 7 items/min)
2022-06-13 11:42:57,698 - retry.py[line:96] - DEBUG: Retrying <GET http://www.59med.com/news/show.php?itemid=133680> (failed 1 times): TCP connection timed out: 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2022-06-13 11:42:57,699 - middlewares.py[line:184] - INFO: 使用代理[42.55.180.247:4231]访问[http://www.59med.com/news/show.php?itemid=133680]
2022-06-13 11:42:59,792 - retry.py[line:118] - ERROR: Gave up retrying <GET http://www.59med.com/news/show.php?itemid=133660> (failed 3 times): Connection was refused by other side: 10061: 由于目标计算机积极拒绝，无法连接。.
2022-06-13 11:42:59,793 - middlewares.py[line:184] - INFO: 使用代理[42.57.148.87:4267]访问[http://www.59med.com/news/show.php?itemid=133660]
2022-06-13 11:42:59,874 - middlewares.py[line:184] - INFO: 使用代理[58.243.28.23:4231]访问[http://www.59med.com/news/list.php?catid=26&page=3]
2022-06-13 11:43:01,299 - middlewares.py[line:184] - INFO: 使用代理[113.229.173.6:4231]访问[http://www.59med.com/news/show.php?itemid=133677]
2022-06-13 11:43:01,950 - retry.py[line:96] - DEBUG: Retrying <GET http://www.59med.com/news/show.php?itemid=133681> (failed 1 times): TCP connection timed out: 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2022-06-13 11:43:01,950 - middlewares.py[line:184] - INFO: 使用代理[123.144.61.224:4235]访问[http://www.59med.com/news/show.php?itemid=133681]
2022-06-13 11:43:02,203 - engine.py[line:291] - DEBUG: Crawled (200) <GET http://www.59med.com/news/list.php?catid=26&page=4> (referer: None)
2022-06-13 11:43:03,435 - retry.py[line:118] - ERROR: Gave up retrying <GET http://www.59med.com/news/show.php?itemid=133667> (failed 3 times): Connection was refused by other side: 10061: 由于目标计算机积极拒绝，无法连接。.
2022-06-13 11:43:03,435 - middlewares.py[line:184] - INFO: 使用代理[123.144.61.224:4235]访问[http://www.59med.com/news/show.php?itemid=133667]
2022-06-13 11:43:04,241 - retry.py[line:118] - ERROR: Gave up retrying <GET http://www.59med.com/news/list.php?catid=26&page=2> (failed 3 times): TCP connection timed out: 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2022-06-13 11:43:04,242 - middlewares.py[line:184] - INFO: 使用代理[113.235.64.200:4243]访问[http://www.59med.com/news/list.php?catid=26&page=2]
2022-06-13 11:43:07,390 - retry.py[line:96] - DEBUG: Retrying <GET http://www.59med.com/news/show.php?itemid=133683> (failed 2 times): TCP connection timed out: 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2022-06-13 11:43:07,391 - middlewares.py[line:184] - INFO: 使用代理[121.29.83.20:4242]访问[http://www.59med.com/news/show.php?itemid=133683]
2022-06-13 11:43:07,936 - retry.py[line:96] - DEBUG: Retrying <GET http://www.59med.com/news/show.php?itemid=133659> (failed 2 times): TCP connection timed out: 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2022-06-13 11:43:07,936 - middlewares.py[line:184] - INFO: 使用代理[175.146.215.46:4256]访问[http://www.59med.com/news/show.php?itemid=133659]
2022-06-13 11:43:08,939 - engine.py[line:291] - DEBUG: Crawled (200) <GET http://www.59med.com/news/show.php?itemid=133660> (referer: http://www.59med.com/news/list.php?catid=26&page=1)
2022-06-13 11:43:09,004 - middlewares.py[line:184] - INFO: 使用代理[42.55.180.247:4231]访问[http://www.59med.com/news/list.php?catid=26&page=3]
2022-06-13 11:43:09,046 - scraper.py[line:275] - DEBUG: Scraped from <200 http://www.59med.com/news/show.php?itemid=133660>
None
2022-06-13 11:43:09,573 - retry.py[line:96] - DEBUG: Retrying <GET http://www.59med.com/news/show.php?itemid=133680> (failed 2 times): Connection was refused by other side: 10061: 由于目标计算机积极拒绝，无法连接。.
2022-06-13 11:43:09,574 - middlewares.py[line:184] - INFO: 使用代理[175.149.61.52:4243]访问[http://www.59med.com/news/show.php?itemid=133680]
2022-06-13 11:43:09,925 - middlewares.py[line:184] - INFO: 使用代理[123.158.98.221:4281]访问[http://www.59med.com/news/show.php?itemid=133681]
2022-06-13 11:43:10,221 - middlewares.py[line:184] - INFO: 使用代理[110.18.2.133:4234]访问[http://www.59med.com/news/show.php?itemid=133667]
2022-06-13 11:43:11,183 - retry.py[line:96] - DEBUG: Retrying <GET http://www.59med.com/news/show.php?itemid=133661> (failed 2 times): TCP connection timed out: 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2022-06-13 11:43:11,184 - middlewares.py[line:184] - INFO: 使用代理[121.29.82.46:4231]访问[http://www.59med.com/news/show.php?itemid=133661]
2022-06-13 11:43:11,544 - retry.py[line:96] - DEBUG: Retrying <GET http://www.59med.com/news/show.php?itemid=133677> (failed 2 times): Connection was refused by other side: 10061: 由于目标计算机积极拒绝，无法连接。.
2022-06-13 11:43:11,545 - middlewares.py[line:184] - INFO: 使用代理[101.27.197.197:4231]访问[http://www.59med.com/news/show.php?itemid=133677]
2022-06-13 11:43:13,331 - retry.py[line:118] - ERROR: Gave up retrying <GET http://www.59med.com/news/show.php?itemid=133683> (failed 3 times): Connection was refused by other side: 10061: 由于目标计算机积极拒绝，无法连接。.
2022-06-13 11:43:13,332 - middlewares.py[line:184] - INFO: 使用代理[121.29.83.20:4242]访问[http://www.59med.com/news/show.php?itemid=133683]
2022-06-13 11:43:13,673 - retry.py[line:96] - DEBUG: Retrying <GET http://www.59med.com/news/show.php?itemid=133664> (failed 2 times): TCP connection timed out: 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2022-06-13 11:43:13,673 - middlewares.py[line:184] - INFO: 使用代理[175.173.220.224:4210]访问[http://www.59med.com/news/show.php?itemid=133664]
2022-06-13 11:43:13,786 - retry.py[line:118] - ERROR: Gave up retrying <GET http://www.59med.com/news/show.php?itemid=133659> (failed 3 times): Connection was refused by other side: 10061: 由于目标计算机积极拒绝，无法连接。.
2022-06-13 11:43:13,787 - middlewares.py[line:184] - INFO: 使用代理[120.2.1.2:4231]访问[http://www.59med.com/news/show.php?itemid=133659]
2022-06-13 11:43:15,551 - retry.py[line:118] - ERROR: Gave up retrying <GET http://www.59med.com/news/list.php?catid=26&page=3> (failed 3 times): Connection was refused by other side: 10061: 由于目标计算机积极拒绝，无法连接。.
2022-06-13 11:43:15,552 - middlewares.py[line:184] - INFO: 使用代理[113.237.185.131:4261]访问[http://www.59med.com/news/list.php?catid=26&page=3]
2022-06-13 11:43:16,251 - retry.py[line:96] - DEBUG: Retrying <GET http://www.59med.com/news/show.php?itemid=133679> (failed 2 times): TCP connection timed out: 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2022-06-13 11:43:16,252 - middlewares.py[line:184] - INFO: 使用代理[116.115.209.177:4231]访问[http://www.59med.com/news/show.php?itemid=133679]
2022-06-13 11:43:16,545 - retry.py[line:118] - ERROR: Gave up retrying <GET http://www.59med.com/news/show.php?itemid=133680> (failed 3 times): Connection was refused by other side: 10061: 由于目标计算机积极拒绝，无法连接。.
2022-06-13 11:43:16,546 - middlewares.py[line:184] - INFO: 使用代理[123.144.61.224:4235]访问[http://www.59med.com/news/show.php?itemid=133680]
2022-06-13 11:43:17,324 - engine.py[line:291] - DEBUG: Crawled (200) <GET http://www.59med.com/news/show.php?itemid=133661> (referer: http://www.59med.com/news/list.php?catid=26&page=1)
2022-06-13 11:43:17,433 - scraper.py[line:275] - DEBUG: Scraped from <200 http://www.59med.com/news/show.php?itemid=133661>
None
2022-06-13 11:43:18,860 - retry.py[line:118] - ERROR: Gave up retrying <GET http://www.59med.com/news/show.php?itemid=133677> (failed 3 times): Connection was refused by other side: 10061: 由于目标计算机积极拒绝，无法连接。.
2022-06-13 11:43:18,861 - middlewares.py[line:184] - INFO: 使用代理[123.144.151.32:4246]访问[http://www.59med.com/news/show.php?itemid=133677]
2022-06-13 11:43:19,432 - retry.py[line:118] - ERROR: Gave up retrying <GET http://www.59med.com/news/show.php?itemid=133683> (failed 3 times): Connection was refused by other side: 10061: 由于目标计算机积极拒绝，无法连接。.
2022-06-13 11:43:19,433 - middlewares.py[line:184] - INFO: 使用代理[42.59.101.204:4213]访问[http://www.59med.com/news/show.php?itemid=133683]
2022-06-13 11:43:23,369 - retry.py[line:96] - DEBUG: Retrying <GET http://www.59med.com/news/show.php?itemid=133684> (failed 2 times): TCP connection timed out: 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2022-06-13 11:43:23,370 - middlewares.py[line:184] - INFO: 使用代理[42.56.237.193:4216]访问[http://www.59med.com/news/show.php?itemid=133684]
2022-06-13 11:43:24,500 - retry.py[line:118] - ERROR: Gave up retrying <GET http://www.59med.com/news/show.php?itemid=133674> (failed 3 times): TCP connection timed out: 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2022-06-13 11:43:24,501 - middlewares.py[line:184] - INFO: 使用代理[42.57.148.87:4267]访问[http://www.59med.com/news/show.php?itemid=133674]
2022-06-13 11:43:25,288 - retry.py[line:118] - ERROR: Gave up retrying <GET http://www.59med.com/news/show.php?itemid=133665> (failed 3 times): TCP connection timed out: 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2022-06-13 11:43:25,289 - middlewares.py[line:184] - INFO: 使用代理[116.115.210.179:4231]访问[http://www.59med.com/news/show.php?itemid=133665]
2022-06-13 11:43:25,376 - middlewares.py[line:184] - INFO: 使用代理[121.29.82.46:4231]访问[http://www.59med.com/news/show.php?itemid=133680]
